export const data = [
  {
    id: 1675,
    model: "Suzuki Baleno GL 2026",
    img: "https://carasti-operations.s3.ap-south-1.amazonaws.com/user-documents/1752496386Image_14_07_2025_at_4.25___PM.jpeg",
    fuel_type: 1,
    listing_price: 1399,
    delivery_method: 2,
    top_deal: 0,
    free_fuel: 0,
    delivery_days: 14,
    new_car: 1,
    available_from: "2025-11-16",
    available: 1,
    car_rate_id: 38335,
    slug: "Suzuki-Baleno-2026-GL-Hatchback",
    brand_value: "Suzuki",
    model_value: "Baleno",
    trim_value: "GL",
    category_value: "Hatchback",
    custom_mileage_allowance: 0,
    custom_mileage_label: "",
    is_weekly: 0,
    car_id: 53970,
    discount_val: 0,
    discount: 0,
    discount_type: 0,
    discount_value: 0,
    discount_text: "",
    discount_color: "",
    coming_soon: false,
    upfront: false,
    upfront_listing_price: 0,
  },
  
  {
    id: 1539,
    model: "Geely CoolRay GL 2025",
    img: "https://carasti-operations.s3.ap-south-1.amazonaws.com/user-documents/1744634008Image_14_04_2025_at_4.29___PM.jpeg",
    fuel_type: 1,
    listing_price: 2199,
    delivery_method: 2,
    top_deal: 1,
    free_fuel: 0,
    delivery_days: 0,
    new_car: 1,
    available_from: "2025-11-02",
    available: 1,
    car_rate_id: 39025,
    slug: "Geely-CoolRay-2025-GL-Crossover",
    brand_value: "Geely",
    model_value: "CoolRay",
    trim_value: "GL",
    category_value: "Crossover",
    custom_mileage_allowance: 0,
    custom_mileage_label: "",
    is_weekly: 0,
    car_id: 54405,
    discount_val: 200,
    discount: 1,
    discount_type: 0,
    discount_value: 200,
    discount_text: "AED 200 OFF",
    discount_color: "02c39A",
    coming_soon: false,
    upfront: false,
    upfront_listing_price: 0,
  },
  
  {
    id: 925,
    model: "MG GT  2023",
    img: "https://carasti-operations.s3.ap-south-1.amazonaws.com/user-documents/1761815941Image_03_03_2025_at_1.50___PM.jpeg",
    fuel_type: 1,
    listing_price: 2699,
    delivery_method: 2,
    top_deal: 0,
    free_fuel: 0,
    delivery_days: 0,
    new_car: 0,
    available_from: "2025-11-03",
    available: 1,
    car_rate_id: 38949,
    slug: "MG-GT-2023-default-Sedan",
    brand_value: "MG",
    model_value: "GT",
    trim_value: "*",
    category_value: "Sedan",
    custom_mileage_allowance: 0,
    custom_mileage_label: "",
    is_weekly: 0,
    car_id: 43077,
    discount_val: 300,
    discount: 1,
    discount_type: 0,
    discount_value: 300,
    discount_text: "AED 300 OFF",
    discount_color: "02c39a",
    coming_soon: false,
    upfront: false,
    upfront_listing_price: 0,
  },
  
  {
    id: 1753,
    model: "Kia Sportage L 2026",
    img: "https://carasti-operations.s3.ap-south-1.amazonaws.com/user-documents/17616504858.png",
    fuel_type: 1,
    listing_price: 2899,
    delivery_method: 2,
    top_deal: 0,
    free_fuel: 0,
    delivery_days: 15,
    new_car: 1,
    available_from: "2025-11-17",
    available: 1,
    car_rate_id: 39019,
    slug: "Kia-Sportage-2026-L-SUV",
    brand_value: "Kia",
    model_value: "Sportage",
    trim_value: "L",
    category_value: "SUV",
    custom_mileage_allowance: 0,
    custom_mileage_label: "",
    is_weekly: 0,
    car_id: 54399,
    discount_val: 0,
    discount: 0,
    discount_type: 0,
    discount_value: 0,
    discount_text: "",
    discount_color: "",
    coming_soon: false,
    upfront: false,
    upfront_listing_price: 0,
  },
  {
    id: 1047,
    model: "Fiat 500X Style RVC Comfort Package 2023",
    img: "https://carasti-operations.s3.ap-south-1.amazonaws.com/user-documents/1761653528Image_28_10_2025_at_4.10___PM.jpeg",
    fuel_type: 1,
    listing_price: 2999,
    delivery_method: 2,
    top_deal: 0,
    free_fuel: 0,
    delivery_days: 0,
    new_car: 0,
    available_from: "2025-11-03",
    available: 1,
    car_rate_id: 38840,
    slug: "Fiat-500X-2023-Style-RVC-Comfort-Package-Crossover",
    brand_value: "Fiat",
    model_value: "500X",
    trim_value: "Style RVC Comfort Package",
    category_value: "Crossover",
    custom_mileage_allowance: 0,
    custom_mileage_label: "",
    is_weekly: 0,
    car_id: 52385,
    discount_val: 0,
    discount: 0,
    discount_type: 0,
    discount_value: 0,
    discount_text: "",
    discount_color: "",
    coming_soon: false,
    upfront: false,
    upfront_listing_price: 0,
  },
  {
    id: 1679,
    model: "Mercedes-Benz A-Class 200 Premium 2026",
    img: "https://carasti-operations.s3.ap-south-1.amazonaws.com/user-documents/1761306080Image_15_07_2025_at_2.18___PM.jpeg",
    fuel_type: 1,
    listing_price: 2999,
    delivery_method: 2,
    top_deal: 0,
    free_fuel: 0,
    delivery_days: 15,
    new_car: 1,
    available_from: "2025-11-17",
    available: 1,
    car_rate_id: 38863,
    slug: "Mercedes-Benz-A-Class-2026-200-Premium-Hatchback",
    brand_value: "Mercedes-Benz",
    model_value: "A-Class",
    trim_value: "200 Premium",
    category_value: "Hatchback",
    custom_mileage_allowance: 0,
    custom_mileage_label: "",
    is_weekly: 0,
    car_id: 54370,
    discount_val: 300,
    discount: 0,
    discount_type: 0,
    discount_value: 0,
    discount_text: "",
    discount_color: "",
    coming_soon: false,
    upfront: false,
    upfront_listing_price: 0,
  },
  {
    id: 1709,
    model: "Ford Territory Trend 2026",
    img: "https://carasti-operations.s3.ap-south-1.amazonaws.com/user-documents/1755700011Green_Blue_and_White_Minimalist_Landscape_Desktop_Wallpaper.png",
    fuel_type: 1,
    listing_price: 3299,
    delivery_method: 2,
    top_deal: 1,
    free_fuel: 0,
    delivery_days: 14,
    new_car: 1,
    available_from: "2025-11-16",
    available: 1,
    car_rate_id: 39014,
    slug: "Ford-Territory-2026-Trend-SUV",
    brand_value: "Ford",
    model_value: "Territory",
    trim_value: "Trend",
    category_value: "Crossover",
    custom_mileage_allowance: 0,
    custom_mileage_label: "",
    is_weekly: 0,
    car_id: 54388,
    discount_val: 400,
    discount: 1,
    discount_type: 0,
    discount_value: 400,
    discount_text: "AED 400 OFF",
    discount_color: "02c39A",
    coming_soon: false,
    upfront: false,
    upfront_listing_price: 0,
  },
  {
    id: 1125,
    model: "GAC Empow  2024",
    img: "https://carasti-operations.s3.ap-south-1.amazonaws.com/user-documents/1759829270Image_07_10_2025_at_1.26___PM.jpeg",
    fuel_type: 1,
    listing_price: 3299,
    delivery_method: 2,
    top_deal: 0,
    free_fuel: 0,
    delivery_days: 0,
    new_car: 0,
    available_from: "2025-11-03",
    available: 1,
    car_rate_id: 38865,
    slug: "GAC-Empow-2024-default-Sedan",
    brand_value: "GAC",
    model_value: "Empow",
    trim_value: "*",
    category_value: "Sedan",
    custom_mileage_allowance: 0,
    custom_mileage_label: "",
    is_weekly: 0,
    car_id: 51289,
    discount_val: 300,
    discount: 1,
    discount_type: 0,
    discount_value: 300,
    discount_text: "AED 300 OFF",
    discount_color: "02c39A",
    coming_soon: false,
    upfront: false,
    upfront_listing_price: 0,
  },
  
  {
    id: 1147,
    model: "Audi Q8 55 TFSI Progress 2024",
    img: "https://carasti-operations.s3.ap-south-1.amazonaws.com/user-documents/1761651056Image_28_10_2025_at_3.30___PM.jpeg",
    fuel_type: 1,
    listing_price: 3499,
    delivery_method: 1,
    top_deal: 0,
    free_fuel: 0,
    delivery_days: 0,
    new_car: 0,
    available_from: "2025-11-03",
    available: 1,
    car_rate_id: 39020,
    slug: "Audi-Q8-2024-55-TFSi-Black-Carbon-SUV",
    brand_value: "Audi",
    model_value: "Q8",
    trim_value: "55 TFSI Progress",
    category_value: "SUV",
    custom_mileage_allowance: 3000,
    custom_mileage_label: "",
    is_weekly: 1,
    car_id: 54398,
    discount_val: 0,
    discount: 0,
    discount_type: 0,
    discount_value: 0,
    discount_text: "",
    discount_color: "",
    coming_soon: false,
    upfront: false,
    upfront_listing_price: 0,
  },
  
  
  {
    id: 1754,
    model: "Ford Everest XLS 2025",
    img: "https://carasti-operations.s3.ap-south-1.amazonaws.com/user-documents/1761655507Image_28_10_2025_at_4.43___PM.jpeg",
    fuel_type: 1,
    listing_price: 4799,
    delivery_method: 2,
    top_deal: 0,
    free_fuel: 0,
    delivery_days: 15,
    new_car: 1,
    available_from: "2025-11-17",
    available: 1,
    car_rate_id: 39024,
    slug: "Ford-Everest-2025-XLS-SUV",
    brand_value: "Ford",
    model_value: "Everest",
    trim_value: "XLS",
    category_value: "SUV",
    custom_mileage_allowance: 0,
    custom_mileage_label: "",
    is_weekly: 0,
    car_id: 54410,
    discount_val: 0,
    discount: 0,
    discount_type: 0,
    discount_value: 0,
    discount_text: "",
    discount_color: "",
    coming_soon: false,
    upfront: false,
    upfront_listing_price: 0,
  },
  
  {
    id: 1089,
    model: "Tesla Model 3 Standard Range 2024",
    img: "https://carasti-operations.s3.ap-south-1.amazonaws.com/user-documents/1740058246_MY2024__White__Tesla_Model_3_Highland_Cover.png",
    fuel_type: 4,
    listing_price: 5499,
    delivery_method: 2,
    top_deal: 0,
    free_fuel: 0,
    delivery_days: 0,
    new_car: 0,
    available_from: "2025-11-03",
    available: 1,
    car_rate_id: 38913,
    slug: "Tesla-Model-3-2024-Single-Motor-Facelift-Model-Sedan",
    brand_value: "Tesla",
    model_value: "Model 3",
    trim_value: "Standard Range",
    category_value: "Sedan",
    custom_mileage_allowance: 0,
    custom_mileage_label: "",
    is_weekly: 0,
    car_id: 54416,
    discount_val: 500,
    discount: 1,
    discount_type: 0,
    discount_value: 500,
    discount_text: "AED 500 OFF",
    discount_color: "02c39A",
    coming_soon: false,
    upfront: false,
    upfront_listing_price: 0,
  },
  
  {
    id: 960,
    model: "Alfa Romeo Stelvio Quadrifoglio 2023",
    img: "https://carasti-operations.s3.ap-south-1.amazonaws.com/user-documents/1761826298Image_28_10_2025_at_2.00___PM.jpeg",
    fuel_type: 1,
    listing_price: 8799,
    delivery_method: 2,
    top_deal: 0,
    free_fuel: 0,
    delivery_days: 0,
    new_car: 0,
    available_from: "2025-11-03",
    available: 1,
    car_rate_id: 38916,
    slug: "Alfa-Romeo-Stelvio-2023-Quadrifoglio-Crossover",
    brand_value: "Alfa Romeo",
    model_value: "Stelvio",
    trim_value: "Quadrifoglio",
    category_value: "Crossover",
    custom_mileage_allowance: 0,
    custom_mileage_label: "",
    is_weekly: 0,
    car_id: 52030,
    discount_val: 0,
    discount: 0,
    discount_type: 0,
    discount_value: 0,
    discount_text: "",
    discount_color: "",
    coming_soon: false,
    upfront: false,
    upfront_listing_price: 0,
  },
  
  {
    id: 1731,
    model: "Audi Q8 55TFSI Progress Black 2025",
    img: "https://carasti-operations.s3.ap-south-1.amazonaws.com/user-documents/1761135566Image_22_10_2025_at_4.15___PM.jpeg",
    fuel_type: 1,
    listing_price: 8999,
    delivery_method: 2,
    top_deal: 1,
    free_fuel: 0,
    delivery_days: 0,
    new_car: 1,
    available_from: "2025-11-03",
    available: 1,
    car_rate_id: 38995,
    slug: "Audi-Q8-2025-55TFSI-Progress-Black-SUV",
    brand_value: "Audi",
    model_value: "Q8",
    trim_value: "55TFSI Progress Black",
    category_value: "SUV",
    custom_mileage_allowance: 0,
    custom_mileage_label: "",
    is_weekly: 0,
    car_id: 54134,
    discount_val: 0,
    discount: 0,
    discount_type: 0,
    discount_value: 0,
    discount_text: "",
    discount_color: "",
    coming_soon: false,
    upfront: false,
    upfront_listing_price: 0,
  },
];
