export const sampleData = [
  {
    id: 1675,
    model: "Suzuki Baleno GL 2026",
    img: "https://carasti-operations.s3.ap-south-1.amazonaws.com/user-documents/1752496386Image_14_07_2025_at_4.25___PM.jpeg",
    fuel_type: 1,
    listing_price: 1399,
    delivery_method: 2,
    top_deal: 0,
    free_fuel: 0,
    delivery_days: 14,
    new_car: 1,
    available_from: "2025-11-16",
    available: 1,
    car_rate_id: 38335,
    slug: "Suzuki-Baleno-2026-GL-Hatchback",
    brand_value: "Suzuki",
    model_value: "Baleno",
    trim_value: "GL",
    category_value: "Hatchback",
    custom_mileage_allowance: 0,
    custom_mileage_label: "",
    is_weekly: 0,
    car_id: 53970,
    discount_val: 0,
    discount: 0,
    discount_type: 0,
    discount_value: 0,
    discount_text: "",
    discount_color: "",
    coming_soon: false,
    upfront: false,
    upfront_listing_price: 0,
  },
  
  {
    id: 1539,
    model: "Geely CoolRay GL 2025",
    img: "https://carasti-operations.s3.ap-south-1.amazonaws.com/user-documents/1744634008Image_14_04_2025_at_4.29___PM.jpeg",
    fuel_type: 1,
    listing_price: 2199,
    delivery_method: 2,
    top_deal: 1,
    free_fuel: 0,
    delivery_days: 0,
    new_car: 1,
    available_from: "2025-11-02",
    available: 1,
    car_rate_id: 39025,
    slug: "Geely-CoolRay-2025-GL-Crossover",
    brand_value: "Geely",
    model_value: "CoolRay",
    trim_value: "GL",
    category_value: "Crossover",
    custom_mileage_allowance: 0,
    custom_mileage_label: "",
    is_weekly: 0,
    car_id: 54405,
    discount_val: 200,
    discount: 1,
    discount_type: 0,
    discount_value: 200,
    discount_text: "AED 200 OFF",
    discount_color: "02c39A",
    coming_soon: false,
    upfront: false,
    upfront_listing_price: 0,
  }
] 
