import "./globals.css";
import { Roboto } from "next/font/google";
import { Poppins } from "next/font/google";

import { NavigationBar } from "@/components/navigation-bar/NavigationBar";

const roboto = Roboto({
  subsets: ["latin"], // Required
  weight: ["400", "700"], // Optional
  style: ["normal", "italic"], // Optional
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose the weights you need
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-gray-200 ${poppins.className}`}
      >
        {<NavigationBar/>}
        {children}
      </body>
    </html>
  );
}
