import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Roboto } from "next/font/google";
import { NavigationBar } from "@/components/navigation-bar/NavigationBar";

const roboto = Roboto({
  subsets: ["latin"], // Required
  weight: ["400", "700"], // Optional
  style: ["normal", "italic"], // Optional
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-gray-200 ${roboto.className}`}
      >
        {<NavigationBar/>}
        {children}
      </body>
    </html>
  );
}
